KP-506 [PagerDuty Create Incident] add Parameters
Kaholo/kaholo-plugin-pagerduty pull request #4
Opened 2022-02-24 12:05 UTC by xkcm

* Add new parameters to **Create Incident** method
* Code refactoring

2022-02-24 16:08 UTC, arispen requested changes

2022-02-24 16:08 UTC, arispen commented on .gitignore
> +yarn.lock
please provide the .gitignore from the plugin template
https://github.com/Kaholo/kaholo-plugin-template

2022-02-24 16:08 UTC, arispen commented on app.js
> +    URGENCY, PRIORITY, ESCALATION_POLICY, CONFERENCE_NUMBER, CONFERENCE_URL,
are we going to parse it in any way?

2022-02-24 16:08 UTC, arispen commented on app.js
> +    SUMMARY, ROUTING_KEY, SOURCE, CUSTOM_DETAILS,
parsing?

2022-02-24 16:08 UTC, arispen commented on autocomplete.js
> +    const result = await performApiRequest({
error handling?

2022-02-24 16:08 UTC, arispen commented on config.json
> +  "version": "1.1.1",
I think you can increase the version to 2.0.0

2022-02-24 16:08 UTC, arispen commented on package.json
> +  "description": "Kaholo Plugin for Datadog",
I think you can remove it

2022-02-24 16:08 UTC, arispen commented on config.json
> +  "description": "Integration with PagerDuty REST API integration",
integration with integration?

2022-02-24 16:08 UTC, arispen commented on config.json
> +          "required": true,
I think we should put required params first

2022-02-24 16:08 UTC, arispen commented on config.json
> +        },
these are not required?

2022-02-24 16:08 UTC, arispen commented on helpers.js
> +    errorResponse = JSON.stringify(responseData);
add error handling for stringify

2022-02-24 16:08 UTC, arispen commented on helpers.js
> + */
I think we can remove jsdocs

2022-02-24 16:08 UTC, arispen commented on helpers.js
> +function tidyObject(o) {
are we sure that there is no better way to handle that using lodash?

2022-02-24 16:24 UTC, xkcm commented on config.json
> +        },
The Token can be provided in the Plugin's settings so it should not be required here, but the Email should be required, thanks for pointing this out.

2022-02-25 08:55 UTC, arispen submitted a review, later dismissed

2022-02-25 10:01 UTC, arispen approved these changes

2022-02-25 10:01 UTC, merged